### ISSUE TITLE
h-m-m --config doesn't work.

### ISSUE THREAD

**Issue by sofomryu** [nadrad/h-m-m#43] opened 2022-11-21 04:42 UTC
Hi, I posted same one in here.

https://github.com/nadrad/h-m-m/issues/42

As you fixed, h-m-m --focus-lock=true test works!
However, setting a config file still doesn't work.
typing 'h-m-m --config=./.h-m-m.conf' still show the same problem in the previous issue.

### Below is my conf file###

![Screenshot from 2022-11-25 19-01-22](https://user-images.githubusercontent.com/69798848/203956907-2ff4b6d0-3666-4765-9f11-79eb74af448d.png)

**Comment by nadrad** [comment] 2022-11-25 07:43
I seems to be working fine! Are you sure the file is `./.h-m-m.conf` and not `./h-m-m.conf`?
Regardless, now it gives an error if you enter a non-existing config file.

**Comment by sofomryu** [comment] 2022-11-25 09:57
> 

I am sure the file is ./.h-m-m.conf
As you said, if I type wrong name of a file, it shows an error that the custom config file doesn't exit!
But, If I type correct conf file, it shows the second image in the referred issue (#42).

**Comment by nadrad** [comment] 2022-11-25 13:08
The problem is with the color values. The "\033" works as a string and not a escape code, and that's why you were seeing its value on the screen instead of seeing its effect. 
It's fixed now. 
Note: remove the quotation marks in the config file.

**Comment by sofomryu** [comment] 2022-11-26 02:41
> The problem is with the color values. The "\033" works as a string and not a escape code, and that's why you were seeing its value on the screen instead of seeing its effect.
> It's fixed now.
> Note: remove the quotation marks in the config file.

Thank you! I have one more question. After removing quotation mark, typing 'h-m-m --config=./.h-m-m.conf" opens a h-m-m file with the config adjusted. But, the config is not adjusted to the whole h-m-m file as a default value. I should add the comment '--config=./.h-m-m.conf' every time I want to adjust the config to a h-m-m file. How can I set the config as a default?

**Comment by nadrad** [comment] 2022-11-29 22:22
Well, you have a few options:

1. move the config file to the default location, or
2. use an environment variable to set the custom location instead of adding it to the command, or
3. create an alias for the command in your shell to run the application with the current arguments.

I personally open it (and other frequently used applications) using a key binding. My key binding runs the following:

`xfce4-terminal -T h-m-m  --working-directory=/mind-maps-path/ --zoom=0.9 -e /path/h-m-m`

In a case like this, you can easily add the config location as an argument as well. Although, I don't do it and use a config file in the default location instead.

**Closed by nadrad** 2022-11-29 22:22 UTC
